name: test

on:
  push:
    branches:
      - test-ci
  # Trigger without any parameters a proactive rebuild
  workflow_dispatch: {}
  workflow_call:
jobs:
  run-linters:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: "true"
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-11-29
          override: true
          components: rustfmt, clippy
      - name: Install Anvil
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: run anvil
        run: anvil -p 8485 &
      - name: kill by port
        run: lsof -ti :8485 | xargs kill -9
      - name: kill by port
        run: lsof -ti :8485 | xargs kill -9
      - name: connect anvil
        run: cast block-number
    